<template>
  <view class="mpb-page"><view class="mpb-safe" /><view class="mpb-header"><button class="mpb-back" aria-label="返回" @click="backOrHome('/pages/user/UserAgentCreationPage')">‹</button><image class="mpb-logo" :src="loginLogo" mode="aspectFit" /><view class="mpb-header-copy"><text class="mpb-title">智能体详情</text><text class="mpb-subtitle">模型、提示词与知识绑定</text></view><text class="mpb-role">普通用户</text></view><view class="mpb-stack"><view v-if="loading" class="mpb-card mpb-empty"><text class="mpb-empty-title">正在加载智能体...</text></view><template v-else-if="agent"><view class="mpb-hero light"><view class="mpb-hero-top"><view><text class="mpb-hero-label">知识智能体</text><text class="mpb-hero-value">{{ rowString(agent, 'name') }}</text></view><text class="mpb-hero-badge purple">{{ statusText(rowString(agent, 'status')) }}</text></view><text class="mpb-hero-copy">{{ rowString(agent, 'description') || '暂无角色说明' }}</text><view class="mpb-hero-metrics"><view class="mpb-hero-metric"><text class="mpb-hero-metric-value">{{ bindings.length }}</text><text class="mpb-hero-metric-label">知识库</text></view><view class="mpb-hero-metric"><text class="mpb-hero-metric-value">{{ rowString(agent, 'modelName') || '默认' }}</text><text class="mpb-hero-metric-label">模型</text></view><view class="mpb-hero-metric"><text class="mpb-hero-metric-value">{{ formatDate(rowString(agent, 'updatedAt', 'createdAt')) }}</text><text class="mpb-hero-metric-label">更新时间</text></view></view></view><view class="mpb-card"><text class="mpb-card-title">系统提示词</text><text class="mpb-card-copy agent-prompt">{{ rowString(agent, 'systemPrompt') || '使用平台默认提示词' }}</text></view><view class="mpb-card mpb-list"><view class="mpb-section-head"><text class="mpb-card-title">知识库绑定</text><text class="mpb-card-copy">{{ bindings.length }} 项</text></view><view v-if="bindings.length" v-for="item in bindings" :key="rowString(item, 'id', 'knowledgeBaseId')" class="mpb-row"><text class="mpb-row-icon green">知</text><view class="mpb-row-main"><text class="mpb-row-title">{{ rowString(item, 'knowledgeBaseName', 'name') || rowString(item, 'knowledgeBaseId') }}</text><text class="mpb-row-meta">{{ rowString(item, 'status') || '已绑定' }}</text></view></view><view v-else class="mpb-empty"><text class="mpb-empty-copy">暂未绑定知识库，智能体仍可使用基础模型回答。</text></view></view><button class="mpb-button" @click="startConversation">使用此智能体验证</button></template><view v-else class="mpb-card mpb-empty"><text class="mpb-empty-title">未找到智能体</text></view></view></view>
</template>
<script setup lang="ts">
import { ref } from "vue"; import { onLoad } from "@dcloudio/uni-app"; import { api } from "../../api/client"; import { asRecord, backOrHome, formatDate, listOf, rowString, statusText, type AnyRecord } from "../../utils/miniProgramBusiness"; import loginLogo from "../../assets/zhiqiyun-logo-transparent.png";
const id=ref("");const loading=ref(false);const agent=ref<AnyRecord|null>(null);const bindings=ref<AnyRecord[]>([]);async function load(){loading.value=true;try{const result=asRecord(await api(`/api/v1/knowledge-agents/${encodeURIComponent(id.value)}`));agent.value=asRecord(result.agent);bindings.value=listOf(result.knowledgeBindings);}catch(error){uni.showToast({title:error instanceof Error?error.message:"智能体加载失败",icon:"none"});}finally{loading.value=false;}}function startConversation(){uni.navigateTo({url:"/pages/user/UserReviewCreationPage"});}onLoad(options=>{id.value=String(options?.id||"");void load();});
</script>
<style>
@import "../../styles/mini-program-business.css";
.agent-prompt { display: block; margin-top: 10px; white-space: pre-wrap; }
</style>
