<template>
  <view class="square-page">
    <view class="page-header"><button @click="back">‹</button><view><text class="page-title">灵感广场</text><text class="page-subtitle">发现创意，生成你的同款作品</text></view><view class="header-space"/></view>
    <view class="search-box"><text>⌕</text><input v-model="keyword" confirm-type="search" placeholder="搜索案例、场景或风格" @confirm="search"/><button v-if="keyword" @click="clearSearch">×</button></view>
    <scroll-view scroll-x class="category-scroll" :show-scrollbar="false"><view class="categories"><button :class="{active:!category}" @click="selectCategory('')">推荐</button><button v-for="item in categories" :key="item.id" :class="{active:category===item.code}" @click="selectCategory(item.code)">{{ item.name }}</button></view></scroll-view>
    <view v-if="loading && !items.length" class="skeleton-grid"><view v-for="n in 6" :key="n" class="skeleton-card"><view/><text/><text/></view></view>
    <view v-else-if="error && !items.length" class="state-box"><text>内容加载失败</text><small>{{ error }}</small><button @click="reload">重新加载</button></view>
    <view v-else-if="!items.length" class="state-box"><text>暂时没有相关灵感</text><small>换个分类或关键词看看</small></view>
    <view v-else class="waterfall"><view class="waterfall-column"><InspirationCard v-for="item in leftItems" :key="item.id" :item="item" @open="openDetail"/></view><view class="waterfall-column"><InspirationCard v-for="item in rightItems" :key="item.id" :item="item" @open="openDetail"/></view></view>
    <view v-if="loading && items.length" class="loading-more">正在加载更多...</view><view v-else-if="items.length && !hasMore" class="loading-more">已经到底了</view>
  </view>
</template>
<script setup lang="ts">
import { computed, ref } from "vue";
import { onLoad, onPullDownRefresh, onReachBottom } from "@dcloudio/uni-app";
import InspirationCard from "../../components/inspiration/InspirationCard.vue";
import { inspirationAPI } from "../../features/inspiration/api";
import type { InspirationCategory, InspirationTemplate } from "../../features/inspiration/types";
const categories=ref<InspirationCategory[]>([]),items=ref<InspirationTemplate[]>([]),loading=ref(false),error=ref(""),hasMore=ref(true),page=ref(1),category=ref(""),keyword=ref("");
const leftItems=computed(()=>items.value.filter((_,index)=>index%2===0)),rightItems=computed(()=>items.value.filter((_,index)=>index%2===1));
async function load(reset=false){if(loading.value||(!reset&&!hasMore.value))return;if(reset){page.value=1;items.value=[];hasMore.value=true}loading.value=true;error.value="";try{const result=await inspirationAPI.list({page:page.value,pageSize:12,category:category.value,q:keyword.value.trim()});items.value=reset?result.items:items.value.concat(result.items);hasMore.value=result.hasMore;page.value+=1}catch(reason){error.value=reason instanceof Error?reason.message:"请稍后重试"}finally{loading.value=false;uni.stopPullDownRefresh()}}
function selectCategory(value:string){if(category.value===value)return;category.value=value;void load(true)}function search(){void load(true)}function clearSearch(){keyword.value="";void load(true)}function reload(){void load(true)}function openDetail(item:InspirationTemplate){uni.navigateTo({url:`/pages/inspiration/InspirationDetailPage?templateId=${encodeURIComponent(item.id)}`})}function back(){uni.navigateBack({fail:()=>uni.switchTab({url:"/pages/user/UserHomePage"})})}
onLoad(async options=>{category.value=String(options?.category||"");try{categories.value=(await inspirationAPI.categories()).items}finally{await load(true)}});onPullDownRefresh(()=>load(true));onReachBottom(()=>load());
</script>
<style scoped>
.square-page{min-height:100vh;padding:calc(16px + env(safe-area-inset-top)) 16px 40px;box-sizing:border-box;color:#151a2b;background:#f6f7fb}.page-header{display:grid;grid-template-columns:42px 1fr 42px;align-items:center}.page-header button{width:38px;height:38px;margin:0;padding:0;border:0;background:transparent;font-size:34px}.page-header button::after,.search-box button::after,.categories button::after,.state-box button::after{display:none}.page-title,.page-subtitle{display:block;text-align:center}.page-title{font-size:22px;font-weight:750}.page-subtitle{margin-top:3px;color:#858da0;font-size:11px}.search-box{display:flex;height:44px;margin-top:18px;padding:0 14px;align-items:center;gap:8px;border:1px solid #e5e8f0;border-radius:22px;background:#fff}.search-box input{min-width:0;flex:1;font-size:13px}.search-box button{width:24px;margin:0;padding:0;border:0;background:transparent;color:#8a92a5}.category-scroll{margin:16px 0}.categories{display:flex;gap:8px;white-space:nowrap}.categories button{width:auto;height:34px;margin:0;padding:0 15px;border:0;border-radius:17px;color:#6f788d;background:#fff;font-size:12px}.categories button.active{color:#fff;background:#4a6cff}.waterfall{display:flex;align-items:flex-start;gap:11px}.waterfall-column{display:flex;min-width:0;flex:1;flex-direction:column;gap:11px}.skeleton-grid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.skeleton-card{height:250px;padding:9px;border-radius:8px;background:#fff}.skeleton-card view,.skeleton-card text{display:block;border-radius:6px;background:#edf0f6;animation:pulse 1.1s infinite}.skeleton-card view{height:180px}.skeleton-card text{width:80%;height:13px;margin-top:10px}.skeleton-card text:last-child{width:55%}.state-box{display:flex;min-height:280px;align-items:center;justify-content:center;flex-direction:column;color:#383f52}.state-box small{margin-top:8px;color:#9299aa}.state-box button{width:auto;margin-top:18px;padding:0 20px;border:0;border-radius:18px;color:#fff;background:#4a6cff;font-size:12px}.loading-more{padding:22px;text-align:center;color:#9299aa;font-size:11px}@keyframes pulse{50%{opacity:.55}}
</style>
