/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ZqAgentCard: typeof import('./../components/zq-agent-card.vue')['default']
    ZqBalanceCard: typeof import('./../components/zq-balance-card.vue')['default']
    ZqFeatureCard: typeof import('./../components/zq-feature-card.vue')['default']
    ZqPageShell: typeof import('./../components/zq-page-shell.vue')['default']
    ZqPlanCard: typeof import('./../components/zq-plan-card.vue')['default']
    ZqWorkCard: typeof import('./../components/zq-work-card.vue')['default']
  }
}
