insert into xz_plans (id, code, name, price_cents, grant_points, duration_days, concurrency, active, entitlements, raw)
values
  ('plan_month', 'basic', 'Basic', 2900, 4000, 30, 3, true, '{"planType":"subscription","billingCycle":"recurring_monthly","audience":"个人、小商家","validityText":"连续包月","displayPrice":"29 元/月","monthlyPoints":4000,"newapiGroup":"basic_group","sort":20}'::jsonb, '{"id":"plan_month","code":"basic","name":"Basic","priceCents":2900,"grantPoints":4000,"durationDays":30,"concurrency":3,"active":true}'::jsonb),
  ('plan_basic_single', 'basic_single', 'Basic 单月购买', 3900, 4000, 30, 3, true, '{"planType":"subscription","billingCycle":"single_month","audience":"个人、小商家","validityText":"单月购买","displayPrice":"39 元/月","monthlyPoints":4000,"newapiGroup":"basic_group","sort":21}'::jsonb, '{"id":"plan_basic_single","code":"basic_single","name":"Basic 单月购买","priceCents":3900,"grantPoints":4000,"durationDays":30,"concurrency":3,"active":true}'::jsonb),
  ('plan_basic_year', 'basic_year', 'Basic 连续包年', 29900, 4000, 365, 3, true, '{"planType":"subscription","billingCycle":"recurring_yearly","audience":"个人、小商家","validityText":"连续包年","displayPrice":"299 元/年","monthlyPoints":4000,"newapiGroup":"basic_group","sort":22}'::jsonb, '{"id":"plan_basic_year","code":"basic_year","name":"Basic 连续包年","priceCents":29900,"grantPoints":4000,"durationDays":365,"concurrency":3,"active":true}'::jsonb),
  ('plan_pro', 'pro', 'Pro', 13900, 20000, 30, 8, true, '{"planType":"subscription","billingCycle":"recurring_monthly","audience":"内容创作者、电商运营","validityText":"连续包月","displayPrice":"139 元/月","monthlyPoints":20000,"newapiGroup":"pro_group","recommended":true,"sort":30}'::jsonb, '{"id":"plan_pro","code":"pro","name":"Pro","priceCents":13900,"grantPoints":20000,"durationDays":30,"concurrency":8,"active":true}'::jsonb),
  ('plan_pro_single', 'pro_single', 'Pro 单月购买', 16900, 20000, 30, 8, true, '{"planType":"subscription","billingCycle":"single_month","audience":"内容创作者、电商运营","validityText":"单月购买","displayPrice":"169 元/月","monthlyPoints":20000,"newapiGroup":"pro_group","recommended":true,"sort":31}'::jsonb, '{"id":"plan_pro_single","code":"pro_single","name":"Pro 单月购买","priceCents":16900,"grantPoints":20000,"durationDays":30,"concurrency":8,"active":true}'::jsonb),
  ('plan_pro_year', 'pro_year', 'Pro 连续包年', 149900, 20000, 365, 8, true, '{"planType":"subscription","billingCycle":"recurring_yearly","audience":"内容创作者、电商运营","validityText":"连续包年","displayPrice":"1499 元/年","monthlyPoints":20000,"newapiGroup":"pro_group","recommended":true,"sort":32}'::jsonb, '{"id":"plan_pro_year","code":"pro_year","name":"Pro 连续包年","priceCents":149900,"grantPoints":20000,"durationDays":365,"concurrency":8,"active":true}'::jsonb),
  ('plan_year', 'ultimate', 'Ultimate', 69900, 100000, 30, 20, true, '{"planType":"subscription","billingCycle":"recurring_monthly","audience":"工作室、代运营团队","validityText":"连续包月","displayPrice":"699 元/月","monthlyPoints":100000,"newapiGroup":"ultimate_group","sort":40}'::jsonb, '{"id":"plan_year","code":"ultimate","name":"Ultimate","priceCents":69900,"grantPoints":100000,"durationDays":30,"concurrency":20,"active":true}'::jsonb),
  ('plan_ultimate_single', 'ultimate_single', 'Ultimate 单月购买', 89900, 100000, 30, 20, true, '{"planType":"subscription","billingCycle":"single_month","audience":"工作室、代运营团队","validityText":"单月购买","displayPrice":"899 元/月","monthlyPoints":100000,"newapiGroup":"ultimate_group","sort":41}'::jsonb, '{"id":"plan_ultimate_single","code":"ultimate_single","name":"Ultimate 单月购买","priceCents":89900,"grantPoints":100000,"durationDays":30,"concurrency":20,"active":true}'::jsonb),
  ('plan_ultimate_year', 'ultimate_year', 'Ultimate 连续包年', 799900, 100000, 365, 20, true, '{"planType":"subscription","billingCycle":"recurring_yearly","audience":"工作室、代运营团队","validityText":"连续包年","displayPrice":"7999 元/年","monthlyPoints":100000,"newapiGroup":"ultimate_group","sort":42}'::jsonb, '{"id":"plan_ultimate_year","code":"ultimate_year","name":"Ultimate 连续包年","priceCents":799900,"grantPoints":100000,"durationDays":365,"concurrency":20,"active":true}'::jsonb),
  ('plan_enterprise', 'enterprise', '企业版', 0, 0, 365, 0, true, '{"planType":"subscription","billingCycle":"custom","audience":"企业客户、代理商","validityText":"定制","displayPrice":"定制","customPrice":true,"customPoints":true,"monthlyPoints":"custom","newapiGroup":"enterprise_group","sort":50}'::jsonb, '{"id":"plan_enterprise","code":"enterprise","name":"企业版","priceCents":0,"grantPoints":0,"durationDays":365,"concurrency":0,"active":true}'::jsonb)
on conflict (id) do update set
  code = excluded.code,
  name = excluded.name,
  price_cents = excluded.price_cents,
  grant_points = excluded.grant_points,
  duration_days = excluded.duration_days,
  concurrency = excluded.concurrency,
  active = excluded.active,
  entitlements = excluded.entitlements,
  raw = excluded.raw;
