<template>
  <section class="media-center">
    <header class="media-page-head">
      <div><el-tag type="success" effect="dark">运营素材</el-tag><h2>素材中心</h2><p>运营图片独立存储，通过素材位发布到小程序，无需重新发版。</p></div>
      <div class="media-head-actions"><el-button @click="openCategoryCreate">新建分类</el-button><el-button type="primary" :icon="Upload" @click="fileInput?.click()">批量上传</el-button><input ref="fileInput" hidden type="file" multiple accept=".jpg,.jpeg,.png,.webp,.avif,.svg" @change="handleFiles" /></div>
    </header>
    <div class="media-layout">
      <aside class="category-panel">
        <strong>素材分类</strong>
        <button :class="{ active: !categoryId }" @click="categoryId = ''; page = 1; loadAssets()"><span>全部素材</span><em>{{ total }}</em></button>
        <button v-for="item in categories" :key="`${item.tenantId}-${item.id}`" :class="{ active: categoryId === item.id }" @click="categoryId = item.id; page = 1; loadAssets()"><span>{{ item.name }}</span><small v-if="item.tenantId === 'default'">平台</small></button>
      </aside>
      <main class="media-main">
        <div class="media-toolbar">
          <el-input v-model="query" clearable placeholder="搜索素材名称" :prefix-icon="Search" @keyup.enter="page = 1; loadAssets()" />
          <el-select v-model="status" clearable placeholder="使用状态" @change="page = 1; loadAssets()"><el-option label="已启用" value="ACTIVE" /><el-option label="已停用" value="DISABLED" /></el-select>
          <el-button :icon="Refresh" @click="loadAll">刷新</el-button>
          <el-radio-group v-model="view"><el-radio-button value="card">卡片</el-radio-button><el-radio-button value="table">表格</el-radio-button></el-radio-group>
        </div>
        <el-progress v-if="uploading" :percentage="uploadProgress" :status="uploadProgress === 100 ? 'success' : undefined" />
        <div v-if="view === 'card'" v-loading="loading" class="asset-grid">
          <article v-for="asset in assets" :key="asset.id" class="asset-card">
            <button class="asset-preview" @click="preview = asset"><img :src="asset.thumbnailUrl || asset.cdnUrl || asset.originalUrl" :alt="asset.name" /><span v-if="asset.isDefault">默认</span></button>
            <div class="asset-card-copy"><strong>{{ asset.name }}</strong><small>{{ asset.width || '-' }} × {{ asset.height || '-' }} · {{ formatBytes(asset.fileSize) }}</small><div><el-tag size="small" :type="asset.status === 'ACTIVE' ? 'success' : 'info'">{{ asset.status === 'ACTIVE' ? '启用' : '停用' }}</el-tag><span>使用 {{ asset.usageCount }} 次</span></div></div>
            <el-dropdown trigger="click" @command="(command: string) => runAssetCommand(command, asset)"><el-button text>操作</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="preview">预览</el-dropdown-item><el-dropdown-item command="edit">编辑名称</el-dropdown-item><el-dropdown-item command="copy">复制链接</el-dropdown-item><el-dropdown-item command="usage">使用位置</el-dropdown-item><el-dropdown-item :command="asset.status === 'ACTIVE' ? 'disable' : 'enable'">{{ asset.status === 'ACTIVE' ? '停用' : '启用' }}</el-dropdown-item><el-dropdown-item command="delete" divided>删除</el-dropdown-item></el-dropdown-menu></template></el-dropdown>
          </article>
          <el-empty v-if="!loading && !assets.length" description="暂无素材，上传第一张运营图片" />
        </div>
        <el-table v-else v-loading="loading" :data="assets" stripe>
          <el-table-column label="预览" width="92"><template #default="scope"><img class="table-thumb" :src="scope.row.thumbnailUrl || scope.row.cdnUrl || scope.row.originalUrl" :alt="scope.row.name" /></template></el-table-column>
          <el-table-column prop="name" label="素材名称" min-width="180" /><el-table-column prop="categoryName" label="分类" min-width="130" /><el-table-column label="格式/尺寸" min-width="150"><template #default="scope">{{ scope.row.fileExt.toUpperCase() }} · {{ scope.row.width }}×{{ scope.row.height }}</template></el-table-column><el-table-column label="大小" width="100"><template #default="scope">{{ formatBytes(scope.row.fileSize) }}</template></el-table-column><el-table-column prop="usageCount" label="使用" width="80" /><el-table-column label="状态" width="90"><template #default="scope"><el-tag size="small" :type="scope.row.status === 'ACTIVE' ? 'success' : 'info'">{{ scope.row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="170"><template #default="scope"><el-button link @click="preview = scope.row">预览</el-button><el-button link @click="showUsages(scope.row)">引用</el-button><el-button link type="danger" @click="removeAsset(scope.row)">删除</el-button></template></el-table-column>
        </el-table>
        <el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next, total" @current-change="loadAssets" />
      </main>
    </div>
    <el-dialog v-model="previewOpen" title="素材预览" width="min(760px, 92vw)"><div v-if="preview" class="preview-dialog"><img :src="preview.cdnUrl || preview.originalUrl" :alt="preview.name" /><dl><div><dt>名称</dt><dd>{{ preview.name }}</dd></div><div><dt>尺寸</dt><dd>{{ preview.width }} × {{ preview.height }}</dd></div><div><dt>哈希</dt><dd><code>{{ preview.fileHash }}</code></dd></div><div><dt>CDN</dt><dd>{{ preview.cdnUrl || preview.originalUrl }}</dd></div></dl></div></el-dialog>
    <el-drawer v-model="usageOpen" title="素材使用位置" size="420px"><el-timeline><el-timeline-item v-for="item in usages" :key="item.id" :timestamp="item.createdAt"><strong>{{ item.pageCode }} / {{ item.moduleCode }}</strong><p>{{ item.slotKey }}</p></el-timeline-item></el-timeline><el-empty v-if="!usages.length" description="当前素材未被引用" /></el-drawer>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { Refresh, Search, Upload } from "@element-plus/icons-vue";
import { createMediaCategory, deleteMediaAsset, listMediaAssets, listMediaAssetUsages, listMediaCategories, setMediaAssetEnabled, updateMediaAsset, uploadMediaAssets, type AssetUsage, type MediaAsset, type MediaCategory } from "../../api/media";
const assets = ref<MediaAsset[]>([]); const categories = ref<MediaCategory[]>([]); const total = ref(0); const page = ref(1); const pageSize = 24; const query = ref(""); const categoryId = ref(""); const status = ref(""); const loading = ref(false); const uploading = ref(false); const uploadProgress = ref(0); const view = ref<"card" | "table">("card"); const fileInput = ref<HTMLInputElement>(); const preview = ref<MediaAsset>(); const usages = ref<AssetUsage[]>([]); const usageOpen = ref(false);
const previewOpen = computed({ get: () => Boolean(preview.value), set: (value) => { if (!value) preview.value = undefined; } });
async function loadAssets(){loading.value=true;try{const response=await listMediaAssets({page:page.value,pageSize,q:query.value,categoryId:categoryId.value,status:status.value});assets.value=response.items;total.value=response.total}catch(error){ElMessage.error(error instanceof Error?error.message:"素材加载失败")}finally{loading.value=false}}
async function loadAll(){try{const response=await listMediaCategories();categories.value=response.items}catch(error){ElMessage.error(error instanceof Error?error.message:"分类加载失败")}await loadAssets()}
async function handleFiles(event:Event){const input=event.target as HTMLInputElement;const files=Array.from(input.files||[]);input.value="";if(!files.length)return;uploading.value=true;uploadProgress.value=0;try{await uploadMediaAssets(files,{categoryId:categoryId.value},value=>uploadProgress.value=value);ElMessage.success(`已上传 ${files.length} 个素材`);await loadAssets()}catch(error){ElMessage.error(error instanceof Error?error.message:"上传失败")}finally{uploading.value=false}}
async function showUsages(asset:MediaAsset){const response=await listMediaAssetUsages(asset.id);usages.value=response.items;usageOpen.value=true}
async function runAssetCommand(command:string,asset:MediaAsset){if(command==="preview")preview.value=asset;else if(command==="usage")await showUsages(asset);else if(command==="copy"){await navigator.clipboard.writeText(asset.cdnUrl||asset.originalUrl||"");ElMessage.success("链接已复制")}else if(command==="edit"){const {value}=await ElMessageBox.prompt("请输入新的素材名称","编辑素材",{inputValue:asset.name});await updateMediaAsset(asset.id,{name:value});await loadAssets()}else if(command==="enable"||command==="disable"){await setMediaAssetEnabled(asset.id,command==="enable");await loadAssets()}else if(command==="delete")await removeAsset(asset)}
async function removeAsset(asset:MediaAsset){try{await ElMessageBox.confirm(`确定删除“${asset.name}”？正在使用的素材会被后端阻止删除。`,"删除素材",{type:"warning"});await deleteMediaAsset(asset.id);ElMessage.success("素材已删除");await loadAssets()}catch(error){if(error!=="cancel"&&error!=="close")ElMessage.error(error instanceof Error?error.message:"删除失败")}}
async function openCategoryCreate(){try{const {value}=await ElMessageBox.prompt("请输入分类名称","新建素材分类");const code=value.trim().toLowerCase().replace(/[^a-z0-9\u4e00-\u9fa5]+/g,"-");await createMediaCategory({name:value,code,sortOrder:categories.value.length*10+10,status:"ACTIVE"});ElMessage.success("分类已创建");await loadAll()}catch(error){if(error!=="cancel"&&error!=="close")ElMessage.error(error instanceof Error?error.message:"创建失败")}}
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${(value/1024).toFixed(1)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
onMounted(loadAll);
</script>

<style scoped>
.media-center{display:grid;gap:18px}.media-page-head{display:flex;align-items:flex-start;justify-content:space-between;padding:24px;border:1px solid #e7e9f2;border-radius:18px;background:linear-gradient(135deg,#fff,#f4f7ff)}.media-page-head h2{margin:10px 0 6px;font-size:26px}.media-page-head p{margin:0;color:#667085}.media-head-actions{display:flex;gap:10px}.media-layout{display:grid;grid-template-columns:210px 1fr;min-height:620px;border:1px solid #e7e9f2;border-radius:18px;background:#fff;overflow:hidden}.category-panel{display:flex;flex-direction:column;gap:6px;padding:18px;border-right:1px solid #eef0f6;background:#fafbfe}.category-panel>strong{margin:2px 8px 12px}.category-panel button{display:flex;align-items:center;justify-content:space-between;border:0;border-radius:10px;padding:10px;background:transparent;color:#475467;text-align:left;cursor:pointer}.category-panel button.active{background:#ebe9ff;color:#5b4ad1;font-weight:700}.category-panel em,.category-panel small{font-style:normal;font-size:11px;color:#98a2b3}.media-main{display:flex;min-width:0;flex-direction:column;gap:16px;padding:18px}.media-toolbar{display:grid;grid-template-columns:minmax(220px,1fr) 150px auto auto;gap:10px}.asset-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:14px;align-content:start}.asset-card{position:relative;border:1px solid #eaecf0;border-radius:14px;overflow:hidden;background:#fff;transition:.2s}.asset-card:hover{transform:translateY(-2px);box-shadow:0 12px 28px #34405418}.asset-preview{position:relative;width:100%;height:142px;border:0;padding:0;background:#f2f4f7;cursor:pointer}.asset-preview img{width:100%;height:100%;object-fit:cover}.asset-preview span{position:absolute;top:8px;left:8px;border-radius:8px;padding:4px 7px;background:#5b4ad1;color:#fff;font-size:11px}.asset-card-copy{display:grid;gap:7px;padding:12px 12px 4px}.asset-card-copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.asset-card-copy small{color:#98a2b3}.asset-card-copy>div{display:flex;align-items:center;justify-content:space-between;color:#667085;font-size:12px}.asset-card>.el-dropdown{padding:2px 6px 8px}.table-thumb{width:56px;height:44px;border-radius:8px;object-fit:cover}.preview-dialog{display:grid;gap:18px}.preview-dialog>img{width:100%;max-height:420px;object-fit:contain;border-radius:12px;background:#f5f6f8}.preview-dialog dl{display:grid;gap:8px;margin:0}.preview-dialog dl div{display:grid;grid-template-columns:80px 1fr;gap:12px}.preview-dialog dt{color:#98a2b3}.preview-dialog dd{margin:0;overflow-wrap:anywhere}.preview-dialog code{font-size:11px}@media(max-width:900px){.media-page-head{gap:18px;flex-direction:column}.media-layout{grid-template-columns:1fr}.category-panel{flex-direction:row;overflow:auto;border-right:0;border-bottom:1px solid #eef0f6}.category-panel>strong{display:none}.media-toolbar{grid-template-columns:1fr 1fr}.asset-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
